### ISSUE TITLE
Chinese Yuan has a few problems

### ISSUE THREAD

**Issue by tomdaffurn** [xsolla/currency-format#9]
Several defects with Chinese Yuan (CNY) in currency-format.json.

1. The name should be 'Chinese Renminbi', not 'Yuan Renminbi'. Yuan is the base unit, equivalent to dollar.
2. The grapheme should be ¥, not 元. 元 is the Chinese character for yuan.
3. Template should be $1 in order to produce ¥100, not 100 ¥.

The Wikipedia article for Renminbi has examples/evidence of all these points.

¥ is also used for JPY, so it's not unique. I don't know what the standard is for a unique symbol (or if there is one)

**Comment by vf-1** [comment]
Suggested modification on CNY and JPY. 

// CNY change of currency name, grapheme and template
> "CNY": {
            "exponent": 2,
            "iso_code": "CNY",
            "iso_numeric": "156",
            "name": "Chinese Renminbi",
            "symbol": {
                "grapheme": "¥",
                "rtl": false,
                "template": "$1"
            }
        },

// JPY removal of the uniqueSymbol secton
>  "JPY": {
            "exponent": 0,
            "iso_code": "JPY",
            "iso_numeric": "392",
            "name": "Yen",
            "symbol": {
                "grapheme": "¥",
                "rtl": false,
                "template": "$1"
            }
        },

**Comment by apigraf** [comment]
Clarified the name of the currency - "Chinese Yuan Renminbi". And fixed the template, from "1 $" to "1$".

We deliberately decided to leave the symbol 元, to preserve the uniqueness of CNY and JPY to display symbols using uniqSymbol. Because two currencies are popular.
And both way of spelling (元 and ¥) are correct to use.

tomdaffurn, "unique symbol" is not standard. We recommend to use uniqSymbol if you want to exclude a repetition of symbols in different currencies.

@tomdaffurn and @vf-1, thank you.
